### ISSUE TITLE
Possible renaming of this project

### ISSUE THREAD

**Issue by pimeys** [pimeys/a2#12]
I've been digging and there's a couple of different apns2 implementations for Rust using the same name. In crates.io the name's been taken by a [curl-based implementation](https://github.com/theduke/apns2-rust) and then we have [the library](https://github.com/polyitan/apns2) I forked this implementation from and which I rewrote, that is pretty high on Google results when you search for `apns2 rust`.

I think this project might need to be renamed, but into what? `tokio-apns2` is kind of meh, and then there's the possibility to go grand and after some Greek gods such as Zeus or Zeus of Tokio...

Any ideas?

**Comment by pimeys** [comment]
https://github.com/theduke/apns2-rust/issues/1

**Comment by pimeys** [comment]
Done. Everybody using this crate should rename references from `apns2` to `a2`. I don't know who else is evaluating this right now, but at least ping @dbrgn .

**Comment by dbrgn** [comment]
Nice :) Thanks for the heads-up.
